GET https://codeit-api-practice.herokuapp.com/api/members

###
POST https://codeit-api-practice.herokuapp.com/api/members
Content-Type: application/json

{
  "name": "Messi",
  "team": "development",
  "position": "IOS Developer",
  "emailAddress": "choiramsey@google.com",
  "phoneNumber": "010-xxxx-xxxx",
  "admissionDate": "2023/02/10",
  "birthday": "1988/11/06",
  "profileImage": "profile1.png"
}

###
PUT https://codeit-api-practice.herokuapp.com/api/members/11111
Content-Type: application/json

{
  "name": "Richalison"
}

###
DELETE https://codeit-api-practice.herokuapp.com/api/members/14